[[HelloWorldC]]
arch = "armv7l"
git-tree-sha1 = "722a356abfd4f06062c97986fce9fd8863cc369c"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "9456633945a755b1cdb3643af1ac147a84244e8966305f51fa247bc5a470af0c"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.0.0+0/HelloWorldC.v1.0.0.arm-linux-gnueabihf.tar.gz"
[[HelloWorldC]]
arch = "aarch64"
git-tree-sha1 = "f890ef264b44a1e354212746f1bb007ab63df25b"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "4acc16997fa679ae5ff7f445e9456eb0ce05dfaa75399cb0176b7a01c0a59b05"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.0.0+0/HelloWorldC.v1.0.0.aarch64-linux-gnu.tar.gz"
[[HelloWorldC]]
arch = "i686"
git-tree-sha1 = "6a61949c0afa5390935db6568ba9a441f8a0c720"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "7172189dee58c8535679dde4c7935e58ab1346785f75740af678be7e707edf73"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.0.0+0/HelloWorldC.v1.0.0.i686-linux-gnu.tar.gz"
[[HelloWorldC]]
arch = "i686"
git-tree-sha1 = "b1e2f7e38678a3a98766cecdbdbe82de95c5f38c"
libc = "musl"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "e0e662343a0076e217fd98db681866d637b9d0770fd0a4165c5e2d15c9aa0542"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.0.0+0/HelloWorldC.v1.0.0.i686-linux-musl.tar.gz"
